In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as  py
df=pd.read_csv("Ecommerce_data.csv")
df.head()

,Order_ID,Order_Date,Delivery_Date,Customer_ID,Category,Product,Quantity,Unit_Price,Discount,Gross_Sales,...,Payment_Method,Order_Status,Sales_Channel,Marketing_Source,Rating,Month,Month_Name,Quarter,Year,Delivery_Days
0,ORD10001,2025-04-13,2025-04-17,CUST1223,Fashion,Sneakers,1,1761.84,0.15,1761.84,...,Wallet,Cancelled,Marketplace,Referral,4.0,4,April,Q2,2025,4
1,ORD10002,2025-12-15,2025-12-19,CUST1446,Fashion,Sneakers,1,4881.69,0.15,4881.69,...,UPI,Delivered,Marketplace,Google Ads,5.0,12,December,Q4,2025,4
2,ORD10003,2025-09-28,2025-09-30,CUST1271,Electronics,Smartphone,1,16778.20,0.10,16778.20,...,UPI,Returned,Website,Facebook Ads,1.0,9,September,Q3,2025,2
3,ORD10004,2025-04-17,2025-04-24,CUST1708,Home & Kitchen,Table Lamp,2,6037.69,0.20,12075.38,...,UPI,Delivered,Mobile App,Email,5.0,4,April,Q2,2025,7
4,ORD10005,2025-03-13,2025-03-14,CUST1672,Books,Data Science Book,2,1880.16,0.20,3760.32,...,Wallet,Returned,Marketplace,Referral,5.0,3,March,Q1,2025,1

In [6]:
df.describe

<bound method NDFrame.describe of       Order_ID  Order_Date Delivery_Date Customer_ID        Category  \
0     ORD10001  2025-04-13    2025-04-17    CUST1223         Fashion
1     ORD10002  2025-12-15    2025-12-19    CUST1446         Fashion
2     ORD10003  2025-09-28    2025-09-30    CUST1271     Electronics
3     ORD10004  2025-04-17    2025-04-24    CUST1708  Home & Kitchen
4     ORD10005  2025-03-13    2025-03-14    CUST1672           Books
...        ...         ...           ...         ...             ...
4995  ORD14996  2025-02-25    2025-03-04    CUST1383         Fashion
4996  ORD14997  2025-12-26    2026-01-01    CUST1105         Grocery
4997  ORD14998  2025-04-20    2025-04-23    CUST1593           Books
4998  ORD14999  2025-07-11    2025-07-18    CUST1446         Fashion
4999  ORD15000  2025-04-03    2025-04-10    CUST1092           Books

                Product  Quantity  Unit_Price  Discount  Gross_Sales  ...  \
0              Sneakers         1     1761.84      0.15      1761.84  ...
1              Sneakers         1     4881.69      0.15      4881.69  ...
2            Smartphone         1    16778.20      0.10     16778.20  ...
3            Table Lamp         2     6037.69      0.20     12075.38  ...
4     Data Science Book         2     1880.16      0.20      3760.32  ...
...                 ...       ...         ...       ...          ...  ...
4995            T-Shirt         3     2180.01      0.00      6540.03  ...
4996           Biscuits         1     1167.76      0.00      1167.76  ...
4997      Business Book         1      540.23      0.10       540.23  ...
4998              Jeans         2     2938.25      0.15      5876.50  ...
4999     Self-Help Book         1     2439.41      0.00      2439.41  ...

      Payment_Method  Order_Status  Sales_Channel  Marketing_Source  Rating  \
0             Wallet     Cancelled    Marketplace          Referral     4.0
1                UPI     Delivered    Marketplace        Google Ads     5.0
2                UPI      Returned        Website      Facebook Ads     1.0
3                UPI     Delivered     Mobile App             Email     5.0
4             Wallet      Returned    Marketplace          Referral     5.0
...              ...           ...            ...               ...     ...
4995     Net Banking     Cancelled     Mobile App         Instagram     5.0
4996     Credit Card     Cancelled        Website             Email     4.0
4997      Debit Card     Delivered     Mobile App        Google Ads     5.0
4998          Wallet     Cancelled     Mobile App             Email     3.0
4999      Debit Card     Delivered        Website           Organic     3.0

     Month Month_Name Quarter  Year Delivery_Days
0        4      April      Q2  2025             4
1       12   December      Q4  2025             4
2        9  September      Q3  2025             2
3        4      April      Q2  2025             7
4        3      March      Q1  2025             1
...    ...        ...     ...   ...           ...
4995     2   February      Q1  2025             7
4996    12   December      Q4  2025             6
4997     4      April      Q2  2025             3
4998     7       July      Q3  2025             7
4999     4      April      Q2  2025             7

[5000 rows x 28 columns]>

In [8]:
df.shape

(5000, 28)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          5000 non-null   str
 1   Order_Date        5000 non-null   str
 2   Delivery_Date     5000 non-null   str
 3   Customer_ID       5000 non-null   str
 4   Category          5000 non-null   str
 5   Product           5000 non-null   str
 6   Quantity          5000 non-null   int64
 7   Unit_Price        5000 non-null   float64
 8   Discount          5000 non-null   float64
 9   Gross_Sales       5000 non-null   float64
 10  Discount_Amount   5000 non-null   float64
 11  Net_Sales         5000 non-null   float64
 12  Shipping_Cost     5000 non-null   int64
 13  Cost              5000 non-null   float64
 14  Profit            5000 non-null   float64
 15  City              5000 non-null   str
 16  State             5000 non-null   str
 17  Customer_Segment  4993 non-null   str
 18  Payment_Method    5000 non-null   str
 19  Order_Status      5000 non-null   str
 20  Sales_Channel     5000 non-null   str
 21  Marketing_Source  4992 non-null   str
 22  Rating            4990 non-null   float64
 23  Month             5000 non-null   int64
 24  Month_Name        5000 non-null   str
 25  Quarter           5000 non-null   str
 26  Year              5000 non-null   int64
 27  Delivery_Days     5000 non-null   int64
dtypes: float64(8), int64(5), str(15)
memory usage: 1.1 MB

In [12]:
df.isnull().sum()

Order_ID             0
Order_Date           0
Delivery_Date        0
Customer_ID          0
Category             0
Product              0
Quantity             0
Unit_Price           0
Discount             0
Gross_Sales          0
Discount_Amount      0
Net_Sales            0
Shipping_Cost        0
Cost                 0
Profit               0
City                 0
State                0
Customer_Segment     7
Payment_Method       0
Order_Status         0
Sales_Channel        0
Marketing_Source     8
Rating              10
Month                0
Month_Name           0
Quarter              0
Year                 0
Delivery_Days        0
dtype: int64

In [13]:
df["Rating"].median()

np.float64(4.0)

In [14]:
df["Rating"]=df["Rating"].fillna(df["Rating"].median())

In [16]:
df.isna().sum()

Order_ID            0
Order_Date          0
Delivery_Date       0
Customer_ID         0
Category            0
Product             0
Quantity            0
Unit_Price          0
Discount            0
Gross_Sales         0
Discount_Amount     0
Net_Sales           0
Shipping_Cost       0
Cost                0
Profit              0
City                0
State               0
Customer_Segment    7
Payment_Method      0
Order_Status        0
Sales_Channel       0
Marketing_Source    8
Rating              0
Month               0
Month_Name          0
Quarter             0
Year                0
Delivery_Days       0
dtype: int64

In [17]:
df.head()

,Order_ID,Order_Date,Delivery_Date,Customer_ID,Category,Product,Quantity,Unit_Price,Discount,Gross_Sales,...,Payment_Method,Order_Status,Sales_Channel,Marketing_Source,Rating,Month,Month_Name,Quarter,Year,Delivery_Days
0,ORD10001,2025-04-13,2025-04-17,CUST1223,Fashion,Sneakers,1,1761.84,0.15,1761.84,...,Wallet,Cancelled,Marketplace,Referral,4.0,4,April,Q2,2025,4
1,ORD10002,2025-12-15,2025-12-19,CUST1446,Fashion,Sneakers,1,4881.69,0.15,4881.69,...,UPI,Delivered,Marketplace,Google Ads,5.0,12,December,Q4,2025,4
2,ORD10003,2025-09-28,2025-09-30,CUST1271,Electronics,Smartphone,1,16778.20,0.10,16778.20,...,UPI,Returned,Website,Facebook Ads,1.0,9,September,Q3,2025,2
3,ORD10004,2025-04-17,2025-04-24,CUST1708,Home & Kitchen,Table Lamp,2,6037.69,0.20,12075.38,...,UPI,Delivered,Mobile App,Email,5.0,4,April,Q2,2025,7
4,ORD10005,2025-03-13,2025-03-14,CUST1672,Books,Data Science Book,2,1880.16,0.20,3760.32,...,Wallet,Returned,Marketplace,Referral,5.0,3,March,Q1,2025,1

In [20]:

pd.set_option('display.max_columns',None)

In [18]:
df.columns

Index(['Order_ID', 'Order_Date', 'Delivery_Date', 'Customer_ID', 'Category',
       'Product', 'Quantity', 'Unit_Price', 'Discount', 'Gross_Sales',
       'Discount_Amount', 'Net_Sales', 'Shipping_Cost', 'Cost', 'Profit',
       'City', 'State', 'Customer_Segment', 'Payment_Method', 'Order_Status',
       'Sales_Channel', 'Marketing_Source', 'Rating', 'Month', 'Month_Name',
       'Quarter', 'Year', 'Delivery_Days'],
      dtype='str')

In [21]:
df.head()

,Order_ID,Order_Date,Delivery_Date,Customer_ID,Category,Product,Quantity,Unit_Price,Discount,Gross_Sales,Discount_Amount,Net_Sales,Shipping_Cost,Cost,Profit,City,State,Customer_Segment,Payment_Method,Order_Status,Sales_Channel,Marketing_Source,Rating,Month,Month_Name,Quarter,Year,Delivery_Days
0,ORD10001,2025-04-13,2025-04-17,CUST1223,Fashion,Sneakers,1,1761.84,0.15,1761.84,264.28,0.00,80,918.23,0.00,Bengaluru,Karnataka,Working Professional,Wallet,Cancelled,Marketplace,Referral,4.0,4,April,Q2,2025,4
1,ORD10002,2025-12-15,2025-12-19,CUST1446,Fashion,Sneakers,1,4881.69,0.15,4881.69,732.25,4149.44,150,2670.19,1329.25,Ahmedabad,Gujarat,Student,UPI,Delivered,Marketplace,Google Ads,5.0,12,December,Q4,2025,4
2,ORD10003,2025-09-28,2025-09-30,CUST1271,Electronics,Smartphone,1,16778.20,0.10,16778.20,1677.82,0.00,80,11825.33,0.00,Delhi,Delhi,Other,UPI,Returned,Website,Facebook Ads,1.0,9,September,Q3,2025,2
3,ORD10004,2025-04-17,2025-04-24,CUST1708,Home & Kitchen,Table Lamp,2,6037.69,0.20,12075.38,2415.08,9660.30,0,7804.93,1855.37,Delhi,Delhi,Business Owner,UPI,Delivered,Mobile App,Email,5.0,4,April,Q2,2025,7
4,ORD10005,2025-03-13,2025-03-14,CUST1672,Books,Data Science Book,2,1880.16,0.20,3760.32,752.06,0.00,150,1861.96,0.00,Nashik,Maharashtra,Business Owner,Wallet,Returned,Marketplace,Referral,5.0,3,March,Q1,2025,1

In [22]:
df["Customer_Segment"].mode()[0]

'Other'

In [23]:
df["Customer_Segment"]=df["Customer_Segment"].fillna(df["Customer_Segment"].mode()[0])

In [24]:
df["Customer_Segment"].isna().sum()

np.int64(0)

In [25]:
df.isna().sum()

Order_ID            0
Order_Date          0
Delivery_Date       0
Customer_ID         0
Category            0
Product             0
Quantity            0
Unit_Price          0
Discount            0
Gross_Sales         0
Discount_Amount     0
Net_Sales           0
Shipping_Cost       0
Cost                0
Profit              0
City                0
State               0
Customer_Segment    0
Payment_Method      0
Order_Status        0
Sales_Channel       0
Marketing_Source    8
Rating              0
Month               0
Month_Name          0
Quarter             0
Year                0
Delivery_Days       0
dtype: int64

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          5000 non-null   str
 1   Order_Date        5000 non-null   str
 2   Delivery_Date     5000 non-null   str
 3   Customer_ID       5000 non-null   str
 4   Category          5000 non-null   str
 5   Product           5000 non-null   str
 6   Quantity          5000 non-null   int64
 7   Unit_Price        5000 non-null   float64
 8   Discount          5000 non-null   float64
 9   Gross_Sales       5000 non-null   float64
 10  Discount_Amount   5000 non-null   float64
 11  Net_Sales         5000 non-null   float64
 12  Shipping_Cost     5000 non-null   int64
 13  Cost              5000 non-null   float64
 14  Profit            5000 non-null   float64
 15  City              5000 non-null   str
 16  State             5000 non-null   str
 17  Customer_Segment  5000 non-null   str
 18  Payment_Method    5000 non-null   str
 19  Order_Status      5000 non-null   str
 20  Sales_Channel     5000 non-null   str
 21  Marketing_Source  4992 non-null   str
 22  Rating            5000 non-null   float64
 23  Month             5000 non-null   int64
 24  Month_Name        5000 non-null   str
 25  Quarter           5000 non-null   str
 26  Year              5000 non-null   int64
 27  Delivery_Days     5000 non-null   int64
dtypes: float64(8), int64(5), str(15)
memory usage: 1.1 MB

In [27]:
df.shape

(5000, 28)

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.dtypes

Order_ID                str
Order_Date              str
Delivery_Date           str
Customer_ID             str
Category                str
Product                 str
Quantity              int64
Unit_Price          float64
Discount            float64
Gross_Sales         float64
Discount_Amount     float64
Net_Sales           float64
Shipping_Cost         int64
Cost                float64
Profit              float64
City                    str
State                   str
Customer_Segment        str
Payment_Method          str
Order_Status            str
Sales_Channel           str
Marketing_Source        str
Rating              float64
Month                 int64
Month_Name              str
Quarter                 str
Year                  int64
Delivery_Days         int64
dtype: object

In [30]:
df["Order_Date"]=pd.to_datetime(df["Order_Date"])
df["Delivery_Date"]=pd.to_datetime(df["Delivery_Date"])

In [31]:
df.dtypes

Order_ID                       str
Order_Date          datetime64[us]
Delivery_Date       datetime64[us]
Customer_ID                    str
Category                       str
Product                        str
Quantity                     int64
Unit_Price                 float64
Discount                   float64
Gross_Sales                float64
Discount_Amount            float64
Net_Sales                  float64
Shipping_Cost                int64
Cost                       float64
Profit                     float64
City                           str
State                          str
Customer_Segment               str
Payment_Method                 str
Order_Status                   str
Sales_Channel                  str
Marketing_Source               str
Rating                     float64
Month                        int64
Month_Name                     str
Quarter                        str
Year                         int64
Delivery_Days                int64
dtype: object

In [32]:
df["Quantity"].describe()

count    5000.000000
mean        1.908200
std         1.112664
min         1.000000
25%         1.000000
50%         2.000000
75%         2.000000
max         5.000000
Name: Quantity, dtype: float64

In [37]:
df[["Unit_Price","Gross_Sales","Net_Sales","Profit"]].describe()

         Unit_Price    Gross_Sales      Net_Sales         Profit
count   5000.000000    5000.000000    5000.000000    5000.000000
mean   11068.841012   20853.843544   13383.291806    3991.768260
std    19513.209815   43567.493560   34417.421858   10917.916542
min       80.020000      80.020000       0.000000    -123.940000
25%     1505.430000    2133.407500       0.000000       0.000000
50%     2972.345000    5212.500000    2283.405000     602.545000
75%     7452.252500   14427.550000    8018.615000    2324.525000
max    84991.150000  410157.350000  390069.550000  156847.240000

In [38]:
df["Discount"].describe()

count    5000.000000
mean        0.115070
std         0.083832
min         0.000000
25%         0.050000
50%         0.100000
75%         0.150000
max         0.300000
Name: Discount, dtype: float64

In [39]:
df[(df["Discount"]<0)| (df["Discount"]>1)].shape[0]

0

In [40]:
df["Rating"].describe

<bound method NDFrame.describe of 0       4.0
1       5.0
2       1.0
3       5.0
4       5.0
       ...
4995    5.0
4996    4.0
4997    5.0
4998    3.0
4999    3.0
Name: Rating, Length: 5000, dtype: float64>

In [41]:
df[(df["Rating"]<1|(df["Rating"]>5))].shape[0]

0

In [34]:
print(df.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['Order_ID', 'Order_Date', 'Delivery_Date', 'Customer_ID', 'Category',
       'Product', 'Quantity', 'Unit_Price', 'Discount', 'Gross_Sales',
       'Discount_Amount', 'Net_Sales', 'Shipping_Cost', 'Cost', 'Profit',
       'City', 'State', 'Customer_Segment', 'Payment_Method', 'Order_Status',
       'Sales_Channel', 'Marketing_Source', 'Rating', 'Month', 'Month_Name',
       'Quarter', 'Year', 'Delivery_Days'],
      dtype='str')>

In [42]:
df["Quantity"].describe()

count    5000.000000
mean        1.908200
std         1.112664
min         1.000000
25%         1.000000
50%         2.000000
75%         2.000000
max         5.000000
Name: Quantity, dtype: float64

In [44]:
df[df["Quantity"]<=0].shape[0]

0

In [46]:
df[df["Unit_Price"]<=0].shape[0]

0

In [47]:
df[df["Profit"]<0].shape[0]

75

In [50]:
df[df["Net_Sales"]<=0].shape[0]

1402

In [52]:
df[df["Net_Sales"]<=0]["Order_Status"].value_counts()

Order_Status
Cancelled    701
Returned     701
Name: count, dtype: int64

In [53]:
df[df["Net_Sales"]<=0][["Order_Status","Net_Sales","Profit"]].head(10)

   Order_Status  Net_Sales  Profit
0     Cancelled        0.0     0.0
2      Returned        0.0     0.0
4      Returned        0.0     0.0
5      Returned        0.0     0.0
9      Returned        0.0     0.0
11    Cancelled        0.0     0.0
17    Cancelled        0.0     0.0
22    Cancelled        0.0     0.0
25     Returned        0.0     0.0
33    Cancelled        0.0     0.0

In [54]:
df["Order_Status"].value_counts()

Order_Status
Delivered    2887
Shipped       711
Cancelled     701
Returned      701
Name: count, dtype: int64

In [56]:
df[["Gross_Sales","Net_Sales","Profit"]].sum()

Gross_Sales    1.042692e+08
Net_Sales      6.691646e+07
Profit         1.995884e+07
dtype: float64